version: "3"

services:
  postgres-data:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=marias
      - POSTGRES_PASSWORD=marias
      - POSTGRES_DB=marias_db
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5431:80

volumes:
  postgres_data:
