version: '3'

services:
  profile-api:
    image: lasmaria/profile.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Profile/API/Dockerfile
    depends_on:
      - postgres-data
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - "5103:80"
      - "50001:50001"


  postgres-data:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=marias
      - POSTGRES_PASSWORD=marias
      - POSTGRES_DB=marias
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5431:80

volumes:
  postgres_data:

