name: development

on:
  push:
    branches: [ dev ]
  #pull_request:
  #  branches: [ dev, main ]

env:
  DOTNET_VERSION: '6.0.101'


jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os : [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Restore packages
      run: dotnet restore LasMarias.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore LasMarias.sln
