#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using HotChocolate;
using HotChocolate.Data;
using LasMarias.Hub.Domain.InputModels.ApplicationUser;
using LasMarias.Hub.Domain.Models;
using Microsoft.AspNetCore.Identity;
using Orun.Domain;

public partial class ApplicationUser: IdentityUser, IApplicationUser
{
    public ApplicationUser()
        {
            Gender = Gender.NotDefined;
        }

        public ApplicationUser(UserCreateInputModel input)
        {
            Id = input.Id;
            UserName = input.UserName;
            NormalizedEmail = input.NormalizedEmail;
            Email = input.Email;
            NormalizedUserName = input.NormalizedUserName;
            EmailConfirmed = input.EmailConfirmed;
            PhoneNumber = input.PhoneNumber;
            PhoneNumberConfirmed = input.PhoneNumberConfirmed;
            FirstName = input.FirstName;
            LastName = input.LastName;
            DNI = input.DNI;
            Gender = Gender.NotDefined;
        }
        
        public string ReferralUserId { get; set; }
        
        public string? ReferenceId { get; set; }
        
        public long? CountryId { get; set; }
        
        public string? FirstName { get; set; }
        
        public string? LastName { get; set; }
        
        [JsonPropertyName("dni")]
        public string? DNI { get; set; }
        
        [JsonPropertyName("passportNumber")]
        public string? PassportNumber { get; set; }
        
        public Gender Gender { get; set; }
        
        /// <summary>
        /// if some user refer business to this user
        /// </summary>
        [JsonIgnore] 
        public virtual IApplicationUser ReferralUser { get; set; }
        
        public virtual ICountry Country { get; set; }
        
        /// <summary>
        /// list of referred users by this user
        /// </summary>
        [JsonIgnore] 
        public virtual ICollection<IApplicationUser> ReferredUsers { get; set; }
        
        /// <summary>
        /// 4 digit token sent to the user when register request is done
        /// </summary>
        [JsonIgnore]
        [GraphQLIgnore]
        public string? VerificationToken { get; set; }
        
        /// <summary>
        /// token generated by the GenerateEmailConfirmationToken of User Manager
        /// </summary>
        [JsonIgnore]
        [GraphQLIgnore]
        public string? VerificationEmailToken { get; set; }
        
        [UseFiltering]
        [UseSorting]
        [JsonIgnore] 
        // [InverseProperty("User")]
        public virtual ICollection<IUserBenefit> UserBenefits { get; set; }


        #region Business Entity members

        public bool Deleted { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        #endregion
}